- name: Configure print server
  import_tasks: config.yml

- name: Secure SSH
  import_tasks: ssh.yml

- name: Install packages
  import_tasks: packages.yml

- name: Configure firewall
  import_tasks: firewall.yml


